"""Add sharing columns

Revision ID: c46c892396fd
Revises: b71e4d2f9130
Create Date: 2026-03-22 10:32:33.436323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46c892396fd'
down_revision: Union[str, Sequence[str], None] = 'b71e4d2f9130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('share_uuid', sa.String(length=36), nullable=True))
    op.add_column('notes', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('notes', sa.Column('is_community', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_notes_share_uuid'), 'notes', ['share_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_share_uuid'), table_name='notes')
    op.drop_column('notes', 'is_community')
    op.drop_column('notes', 'is_published')
    op.drop_column('notes', 'share_uuid')
    # ### end Alembic commands ###
