from pydantic import BaseModel, Field
from datetime import datetime


class NoteCreate(BaseModel):
    """
    INPUT schema for creating a new note.

    The client sends: { "title": "My Note", "content": "This is the content." }
    The client does NOT send: id, user_id, created_at, updated_at
    Those are generated by the server/database.
    """
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)


class NoteResponse(BaseModel):
    """
    OUTPUT schema for returning a note to the client (authenticated routes).

    from_attributes = True tells Pydantic:
    "You'll receive a SQLAlchemy Note object, not a dictionary.
     Read its attributes (note.id, note.title) instead of dict keys."
    """
    id: int
    user_id: int
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)
    is_pinned: bool = False
    share_uuid: str | None = None
    is_published: bool = False
    is_community: bool = False
    created_at: datetime
    updated_at: datetime | None = None  # None because it's null until first update

    class Config:
        from_attributes = True


class CommunityNoteResponse(BaseModel):
    """
    OUTPUT schema for community notes.

    Includes the author's display name instead of exposing user_id.
    """
    id: int
    author_name: str
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)
    is_pinned: bool = False
    share_uuid: str | None = None
    is_published: bool = False
    is_community: bool = False
    like_count: int = 0
    view_count: int = 0
    created_at: datetime
    updated_at: datetime | None = None

    class Config:
        from_attributes = True


class PublicNoteResponse(BaseModel):
    """
    OUTPUT schema for public note endpoints (unauthenticated).
    
    Excludes sensitive fields like user_id to prevent data leakage.
    """
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)
    share_uuid: str
    is_published: bool = False
    is_community: bool = False
    like_count: int = 0
    view_count: int = 0
    created_at: datetime
    updated_at: datetime | None = None

    class Config:
        from_attributes = True


class PaginatedNoteResponse(BaseModel):
    data: list[NoteResponse]
    next_cursor: int | None = None


class PaginatedCommunityNoteResponse(BaseModel):
    data: list[CommunityNoteResponse]
    next_cursor: int | None = None


class NoteVersionSummaryResponse(BaseModel):
    id: int
    version_number: int
    title: str
    created_at: datetime

    class Config:
        from_attributes = True


class NoteVersionResponse(BaseModel):
    id: int
    note_id: int
    version_number: int
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)
    created_at: datetime

    class Config:
        from_attributes = True


class LikeToggleResponse(BaseModel):
    liked: bool
    like_count: int


class NoteUpdate(BaseModel):
    """
    INPUT schema for updating an existing note.

    The client can send either or both fields to update:
    { "title": "Updated Title" }
    { "content": "Updated content." }
    { "title": "New Title", "content": "New content." }

    All fields are optional because the client might want to update just one.
    """
    title: str | None = None
    content: str | None = None
    tags: list[str] | None = None
    is_published: bool | None = None
    is_community: bool | None = None
